#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHIVPNc
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BL")]
	public partial class NHIDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void Inserttbl_download(tbl_download instance);
    partial void Updatetbl_download(tbl_download instance);
    partial void Deletetbl_download(tbl_download instance);
    #endregion
		
		public NHIDataContext() : 
				base(global::NHIVPNc.Properties.Settings.Default.BLConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NHIDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NHIDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NHIDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NHIDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_download> tbl_download
		{
			get
			{
				return this.GetTable<tbl_download>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_download")]
	public partial class tbl_download : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _f_name;
		
		private string _f_remark;
		
		private string _remark;
		
		private System.DateTime _SDATE;
		
		private System.Nullable<bool> _download;
		
		private System.Nullable<System.DateTime> _QDATE;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onf_nameChanging(string value);
    partial void Onf_nameChanged();
    partial void Onf_remarkChanging(string value);
    partial void Onf_remarkChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void OnSDATEChanging(System.DateTime value);
    partial void OnSDATEChanged();
    partial void OndownloadChanging(System.Nullable<bool> value);
    partial void OndownloadChanged();
    partial void OnQDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnQDATEChanged();
    #endregion
		
		public tbl_download()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string f_name
		{
			get
			{
				return this._f_name;
			}
			set
			{
				if ((this._f_name != value))
				{
					this.Onf_nameChanging(value);
					this.SendPropertyChanging();
					this._f_name = value;
					this.SendPropertyChanged("f_name");
					this.Onf_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_remark", DbType="NVarChar(200)")]
		public string f_remark
		{
			get
			{
				return this._f_remark;
			}
			set
			{
				if ((this._f_remark != value))
				{
					this.Onf_remarkChanging(value);
					this.SendPropertyChanging();
					this._f_remark = value;
					this.SendPropertyChanged("f_remark");
					this.Onf_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NVarChar(200)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this.OnSDATEChanging(value);
					this.SendPropertyChanging();
					this._SDATE = value;
					this.SendPropertyChanged("SDATE");
					this.OnSDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_download", DbType="Bit")]
		public System.Nullable<bool> download
		{
			get
			{
				return this._download;
			}
			set
			{
				if ((this._download != value))
				{
					this.OndownloadChanging(value);
					this.SendPropertyChanging();
					this._download = value;
					this.SendPropertyChanged("download");
					this.OndownloadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> QDATE
		{
			get
			{
				return this._QDATE;
			}
			set
			{
				if ((this._QDATE != value))
				{
					this.OnQDATEChanging(value);
					this.SendPropertyChanging();
					this._QDATE = value;
					this.SendPropertyChanged("QDATE");
					this.OnQDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
